import ExampleComponent from '@/components/ExampleComponent';
import ExampleCompositionComponent from '@/components/ExampleCompositionComponent';
import Head from 'next/head';
import { Fragment } from 'react';

//#region Styled Components

//#endregion

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.icso" />
      </Head>
      <ExampleCompositionComponent name="This is Composition Exammple Component" header={<ExampleComponent name="Header" />} footer={<ExampleComponent name="Footer" />}>
        <ExampleComponent name="Children" />
      </ExampleCompositionComponent>
    </Fragment>
  );
}
