import Head from "next/head";
import { Fragment } from "react";
import tw from "tailwind-styled-components";

//#region Styled Components
const Row = tw.div`w-[100px] h-[100px] bg-pink`;

//#endregion

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.icso" />
      </Head>
      <Row>fgsdfsd</Row>
      <div className="bg-">fgsdfsd</div>
    </Fragment>
  );
}
